services:
  #  APPS
  sarah:
    build: .
    ports:
      - "8080:8080"
    environment:
      Instance: "sarah"
      instance_name: "sarah"
      spring.data.mongodb.uri: mongodb://root:example@localhost:27017/sarah_52_24489?authSource=admin
      spring.data.mongodb.database: sarah_52_24489

  mohamed:
    build: .
    ports:
      - "8081:8080"
    environment:
      Instance: "mohamed"
      instance_name: "mohamed"
      spring.data.mongodb.uri: mongodb://root:example@localhost:27017/sarah_52_24489?authSource=admin
      spring.data.mongodb.database: sarah_52_24489

  # MongoDB
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_ROOT_DATABASE: sarah_52_24489
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "9000:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  # Nginx
  nginx:
    image: nginx
    ports:
      - "24489:80"
    volumes:
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - sarah
      - mohamed